[package]
name = "frihart"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Frihart browser binary"
publish.workspace = true

[[bin]]
name = "frihart"
path = "src/main.rs"

[dependencies]
clap.workspace = true
frihart-chrome.workspace = true
frihart-core.workspace = true
frihart-platform.workspace = true
frihart-profile.workspace = true
