[package]
name = "frihart-profile"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "On-disk and ephemeral user profiles"
publish.workspace = true

[dependencies]
frihart-config.workspace = true
frihart-core.workspace = true
frihart-platform.workspace = true
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
